apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: db-credentials-keys 
    creationPolicy: Owner 
  data:
    - secretKey: username
      remoteRef:
        key: db/credentials
        property: DB_USER
    - secretKey: password
      remoteRef:
        key: db/credentials
        property: DB_PASSWORD

