apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox:1.35.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials-keys
            key: password
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials-keys
            key: username
  restartPolicy: Always
